Improving doc for deprecation "deprecated-run-loop-and-computed-dot-a…
ember-learn/deprecation-app pull request #1069
Opened 2022-01-25 00:35 UTC by locks

…ccess"

Source: https://github.com/emberjs/ember.js/pull/19653/files
Note: The properties are listed per-line for ease of writing, but they will be displayed inline in the rendered document because markdown.

2022-01-25 00:36 UTC, locks commented
Recreation of https://github.com/ember-learn/deprecation-app/pull/999. I was going to close and reopen to kick CI into starting, but the forked repo is gone so GH wouldn't let me.

2022-01-27 19:30 UTC, bertdeblock commented on content/ember/v3/deprecated-run-loop-and-computed-dot-access.md
> +And here is the complete list of deprecated funcitons from `run`:
```suggestion
And here is the complete list of deprecated functions from `run`:
```

2022-02-10 14:12 UTC, jaredgalanis requested changes

2022-02-10 14:12 UTC, jaredgalanis commented on content/ember/v3/deprecated-run-loop-and-computed-dot-access.md
> +`computed.oneWay`,
duplicate 
```suggestion
```

2022-03-04 01:15 UTC, merged