Deprecate auto-location
ember-learn/deprecation-app pull request #882
Opened 2021-06-17 18:16 UTC by sandstrom

This should not be merged before https://github.com/emberjs/ember.js/pull/19510 has been merged.

2021-07-17 12:16 UTC, mixonic requested changes

2021-07-17 12:16 UTC, mixonic commented on content/ember/v3/auto-location.md
> +since: '3.28'
```suggestion
until: '5.0.0'
since: '4.0'
```

2021-09-04 17:33 UTC, sandstrom commented
@mixonic I've updated the target to 5.0.0

Set since to 4.1.0, but let me know if we should drop down to 4.0.0.

2021-12-20 17:42 UTC, locks commented
Thanks for working on this @sandstrom!

2021-12-20 17:43 UTC, locks approved these changes

2021-12-20 17:43 UTC, merged